In [212]:
import math
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn as sk
import seaborn as sns
from sklearn import metrics
from sklearn import model_selection
from sklearn import preprocessing
from matplotlib.pyplot import figure

# Classification

In [22]:
ionosphere_data = pd.read_csv('./ionosphere_data.csv', header=None)
ionosphere_data[34] = ionosphere_data[34].apply(lambda x: 1 if x == 'g' else 0)
ionosphere_data

0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
5     1   0  0.02337 -0.00592 -0.09924 -0.11949 -0.00763 -0.11824  0.14706   
6     1   0  0.97588 -0.10602  0.94601 -0.20800  0.92806 -0.28350  0.85996   
7     0   0  0.00000  0.00000  0.00000  0.00000  1.00000 -1.00000  0.00000   
8     1   0  0.96355 -0.07198  1.00000 -0.14333  1.00000 -0.21313  1.00000   
9     1   0 -0.01864 -0.08459  0.00000  0.00000  0.00000  0.00000  0.11470   
10    1   0  1.00000  0.06655  1.00000 -0.18388  1.00000 -0.27320  1.00000   
11    1   0  1.00000 -0.54210  1.00000 -1.00000  1.00000 -1.00000  1.00000   
12    1   0  1.00000 -0.16316  1.00000 -0.10169  0.99999 -0.15197  1.00000   
13    1   0  1.00000 -0.86701  1.00000  0.22280  0.85492 -0.39896  1.00000   
14    1   0  1.00000  0.07380  1.00000  0.03420  1.00000 -0.05563  1.00000   
15    1   0  0.50932 -0.93996  1.00000  0.26708 -0.03520 -1.00000  1.00000   
16    1   0  0.99645  0.06468  1.00000 -0.01236  0.97811  0.02498  0.96112   
17    0   0  0.00000  0.00000 -1.00000 -1.00000  1.00000  1.00000 -1.00000   
18    1   0  0.67065  0.02528  0.66626  0.05031  0.57197  0.18761  0.08776   
19    0   0  1.00000 -1.00000  0.00000  0.00000  0.00000  0.00000  1.00000   
20    1   0  1.00000 -0.00612  1.00000 -0.09834  1.00000 -0.07649  1.00000   
21    0   0  1.00000  1.00000  0.00000  0.00000  0.00000  0.00000 -1.00000   
22    1   0  0.96071  0.07088  1.00000  0.04296  1.00000  0.09313  0.90169   
23    0   0 -1.00000  1.00000  0.00000  0.00000  0.00000  0.00000 -1.00000   
24    1   0  1.00000 -0.06182  1.00000  0.02942  1.00000 -0.05131  1.00000   
25    1   0  1.00000  0.57820  1.00000 -1.00000  1.00000 -1.00000  1.00000   
26    1   0  1.00000 -0.08714  1.00000 -0.17263  0.86635 -0.81779  0.94817   
27    0   0 -1.00000 -1.00000  0.00000  0.00000 -1.00000  1.00000  1.00000   
28    1   0  1.00000  0.08380  1.00000  0.17387  1.00000 -0.13308  0.98172   
29    0   0 -1.00000 -1.00000  1.00000  1.00000  1.00000 -1.00000 -1.00000   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
321   1   0  0.89505 -0.03168  0.87525  0.05545  0.89505  0.01386  0.92871   
322   1   0  0.90071  0.01773  1.00000 -0.01773  0.90071  0.00709  0.84752   
323   1   0  0.39394 -0.24242  0.62655  0.01270  0.45455  0.09091  0.63636   
324   1   0  0.86689  0.35950  0.72014  0.66667  0.37201  0.83049  0.08646   
325   1   0  0.89563  0.37917  0.67311  0.69438  0.35916  0.88696 -0.04193   
326   1   0  0.90547  0.41113  0.65354  0.74761  0.29921  0.95905 -0.13342   
327   1   0  1.00000  1.00000  0.36700  0.06158  0.12993  0.92713 -0.27586   
328   1   0  1.00000  0.51515  0.45455  0.33333  0.06061  0.36364 -0.32104   
329   1   0  0.88110  0.00000  0.94817 -0.02744  0.93598 -0.01220  0.90244   
330   1   0  0.82624  0.08156  0.79078 -0.08156  0.90426 -0.01773  0.92908   
331   1   0  0.74468  0.10638  0.88706  0.00982  0.88542  0.01471  0.87234   
332   1   0  0.87578  0.03727  0.89951  0.00343  0.89210  0.00510  0.86335   
333   1   0  0.97513  0.00710  0.98579  0.01954  1.00000  0.01954  0.99290   
334   1   0  1.00000  0.01105  1.00000  0.01105  1.00000  0.02320  0.99448   
335   1   0  1.00000 -0.01342  1.00000  0.01566  1.00000 -0.00224  1.00000   
336   1   0  0.88420  0.36724  0.67123  0.67382  0.39613  0.86399  0.02424   
337   1   0  0.90147  0.41786  0.64131  0.75725  0.30440  0.95148 -0.20449   
338   1   0  0.32789  0.11042  0.15970  0.29308  0.14020  0.74485 -0.25131   
339   1   0  0.65845  0.43617  0.44681  0.74804  0.05319  0.85106 -0.32027   
340   1   0  0.19466  0.057

In [23]:
ionosphere_data.describe()

0      1           2           3           4           5   \
count  351.000000  351.0  351.000000  351.000000  351.000000  351.000000   
mean     0.891738    0.0    0.641342    0.044372    0.601068    0.115889   
std      0.311155    0.0    0.497708    0.441435    0.519862    0.460810   
min      0.000000    0.0   -1.000000   -1.000000   -1.000000   -1.000000   
25%      1.000000    0.0    0.472135   -0.064735    0.412660   -0.024795   
50%      1.000000    0.0    0.871110    0.016310    0.809200    0.022800   
75%      1.000000    0.0    1.000000    0.194185    1.000000    0.334655   
max      1.000000    0.0    1.000000    1.000000    1.000000    1.000000   

               6           7           8           9      ...              25  \
count  351.000000  351.000000  351.000000  351.000000     ...      351.000000   
mean     0.550095    0.119360    0.511848    0.181345     ...       -0.071187   
std      0.492654    0.520750    0.507066    0.483851     ...        0.508495   
min     -1.000000   -1.000000   -1.000000   -1.000000     ...       -1.000000   
25%      0.211310   -0.054840    0.087110   -0.048075     ...       -0.332390   
50%      0.728730    0.014710    0.684210    0.018290     ...       -0.015050   
75%      0.969240    0.445675    0.953240    0.534195     ...        0.156765   
max      1.000000    1.000000    1.000000    1.000000     ...        1.000000   

               26          27          28          29          30          31  \
count  351.000000  351.000000  351.000000  351.000000  351.000000  351.000000   
mean     0.541641   -0.069538    0.378445   -0.027907    0.352514   -0.003794   
std      0.516205    0.550025    0.575886    0.507974    0.571483    0.513574   
min     -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   
25%      0.286435   -0.443165    0.000000   -0.236885    0.000000   -0.242595   
50%      0.708240   -0.017690    0.496640    0.000000    0.442770    0.000000   
75%      0.999945    0.153535    0.883465    0.154075    0.857620    0.200120   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

               32          33          34  
count  351.000000  351.000000  351.000000  
mean     0.349364    0.014480    0.641026  
std      0.522663    0.468337    0.480384  
min     -1.000000   -1.000000    0.000000  
25%      0.000000   -0.165350    0.000000  
50%      0.409560    0.000000    1.000000  
75%      0.813765    0.171660    1.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 35 columns]

# Neural network

In [213]:
y = ionosphere_data[34]
X = ionosphere_data.drop(axis=1, columns=[34])

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2)

X_train = np.array(X_train)
X_test = np.array(X_test)
y_test = y_test.values.reshape(len(y_test), 1)
y_train = y_train.values.reshape(len(y_train), 1)

In [214]:
class NeuralNetwork:
    def __init__(self, structure, learning_rate = 0.01, batch_size=32):
        self.w0 = np.random.rand(structure[0], structure[1])
        self.w1 = np.random.rand(structure[1], structure[2])
        self.w2 = np.random.rand(structure[2], structure[3])

        self.learning_rate = learning_rate
        self.batch_size = batch_size
        
    def feedforward(self, X):
        self.layer0 = X
        self.layer1 = self.sigmoid(np.dot(self.layer0, self.w0))
        self.layer2 = self.sigmoid(np.dot(self.layer1, self.w1))
        self.layer3 = self.softmax(np.dot(self.layer2, self.w2))
        
        return self.layer3
        
    def backprop(self, X, y_target, y_pred):
        layer3_error = y_pred
        layer3_error[range(len(y_target)), y_target.flatten()] -= 1
        layer3_delta = layer3_error * 1

        layer2_error = layer3_delta.dot(self.w2.T)
        layer2_delta = layer2_error * self.sigmoid_derivative(self.layer2)
        
        layer1_error = layer2_delta.dot(self.w1.T)
        layer1_delta = layer1_error * self.sigmoid_derivative(self.layer1)

        self.w2 -= self.layer2.T.dot(layer3_delta) * self.learning_rate
        self.w1 -= self.layer1.T.dot(layer2_delta) * self.learning_rate
        self.w0 -= self.layer0.T.dot(layer1_delta) * self.learning_rate
        
    def softmax(self, x):
        exp = np.exp(x)
        return exp / np.sum(exp, axis=1, keepdims=True)
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, s):
        return s * (1 - s)
    
    def predict(self, x):
        probs = self.feedforward(x)
        return np.argmax(probs, axis=1)
    
    def train(self, X, y_target, epochs=1000):
        num_train = len(X)
        for i in xrange(epochs):
            for start_idx in range(0, num_train, self.batch_size):
                X_batch = X[start_idx:start_idx+self.batch_size,:]
                y_batch = y_target[start_idx:start_idx+self.batch_size,:]
                
                y_pred = self.feedforward(X_batch)
                self.backprop(X_batch, y_batch, y_pred)
    
    def calculate_loss(self, X, y):
        probs = self.feedforward(X)
        corect_logprobs = -np.log(probs[np.arange(y.shape[0]), y.flatten()])
        data_loss = np.sum(corect_logprobs)
        return data_loss

In [247]:
NN = NeuralNetwork(structure=[X_train.shape[1], 10, 10, 2], learning_rate=0.01)
NN.train(X_train, y_train, epochs=1000000)

In [248]:
NN.calculate_loss(X_train, y_train)

0.00011516052001408999

In [249]:
NN.predict(X_test)

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0])

In [250]:
y_test.flatten()

array([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0])

In [251]:
NN.calculate_loss(X_test, y_test)

96.03108698076817

In [252]:
sklearn.metrics.accuracy_score(y_pred=NN.predict(X_test),y_true=y_test)

0.9154929577464789

In [253]:
sklearn.metrics.confusion_matrix(y_pred=NN.predict(X_test),y_true=y_test)

array([[19,  4],
       [ 2, 46]])